server {
    listen 8080;
    root www;

    location / {
        root www;
        allow_methods GET POST DELETE;
    }

    location /images {
        root www/images;
        allow_methods GET;
        autoindex on;
    }

    location /images/private {
        root www/private;
        allow_methods GET;
    }

    location /cgi {
        root www/cgi-bin/;
        allow_methods GET POST;
        cgi_extension .py /usr/bin/python3;
        cgi_extension .php /usr/bin/php-cgi;
        cgi_extension .bad /path/does/not/exist;
    }
	
	location /foo {
		# no root
        allow_methods GET;
	}
}

server {
    listen 8081;
    root www2;

    location / {
        root www2;
        allow_methods GET;
    }
}
