location / {
    root www;
}

location /images {
    root www/images;
}

location /images/private {
    root www/private;
}

location /cgi {
    root www/cgi-bin/;

    cgi .py /usr/bin/python3;
    cgi .php /usr/bin/php-cgi;
}