server {
    listen 8080;
    server_name localhost;
    root www;

    # Maximum request body size: 1 MB
    client_max_body_size 1048576;

    # Custom error pages
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;

    # Main static website
    # Demonstrates GET, POST and DELETE
    location / {
        root www;
        index index.html;
        allow_methods GET POST DELETE;
    }

    # GET-only route
    # Useful to demonstrate 405 Method Not Allowed
    location /readonly {
        root www/readonly;
        index index.html;
        allow_methods GET;
    }

    # Directory listing enabled
    location /listing {
        root www/listing;
        allow_methods GET;
        autoindex on;
    }

    # Directory listing disabled
    location /no-listing {
        root www/no-listing;
        allow_methods GET;
        autoindex off;
    }

    # Custom default index file
    location /custom-index {
        root www/custom-index;
        index home.html;
        allow_methods GET;
    }

    # HTTP redirection
    location /old {
        redirect /new;
    }

    # Upload authorization and custom storage directory
    location /upload {
        root www;
        allow_methods POST;
        upload_enabled on;
        upload_path www/uploads;
    }

    # CGI execution
    location /cgi {
        root www/cgi-bin/;
        allow_methods GET POST;
        cgi_extension .py /usr/bin/python3;
        cgi_extension .php /usr/bin/php-cgi;
    }
}


# Second website on another port.
# Demonstrates that the same webserv process listens on multiple ports
# and serves different content.
server {
    listen 8081;
    server_name localhost;
    root www2;

    client_max_body_size 1048576;

    error_page 404 /errors/404.html;

    location / {
        root www2;
        index index.html;
        allow_methods GET POST DELETE;
    }
}